"""The comparison, written out.

Markdown for a repository, HTML for the app and for printing. Same content:
one row per prompt, one column per run, labelled with what was under test.

Changed rows come first and are marked. A comparison that buries the two rows
that moved among ninety that did not is a comparison nobody reads twice.
"""

from __future__ import annotations

import html
from pathlib import Path

from understudy.compare import Comparison, Row
from understudy.transcript_html import STYLE, THEME_SCRIPT, _e

MARKS = {
    "same": ("", "unchanged"),
    "reworded": ("~", "same answer, worded differently"),
    "changed": ("!", "the answer moved"),
    "missing": ("?", "not present in every run"),
    "failed": ("x", "a run failed on this prompt"),
}


def render_markdown(comparison: Comparison) -> str:
    out = ["# Comparison", ""]
    if comparison.mixed_flows:
        out += [f"> **These runs are of different flows** "
                f"({', '.join(comparison.flows)}). The rows below are matched "
                f"on prompt id, which may not mean what you want.", ""]

    out += ["| run | under test | when |", "|---|---|---|"]
    for column in comparison.columns:
        out.append(f"| `{column.label}` | {column.subject.summary() or '—'} "
                   f"| {column.timestamp or '—'} |")

    out += ["", f"**{comparison.headline()}**", ""]

    heads = " | ".join(_escape(c.heading) for c in comparison.columns)
    rules = "|".join(["---"] * (len(comparison.columns) + 2))
    out += [f"| | prompt | {heads} |", f"|{rules}|"]

    for row in _ordered(comparison):
        mark = MARKS[row.verdict][0]
        cells = " | ".join(
            "_(no run)_" if r is None else _escape(r) or "_(nothing)_"
            for r in row.responses
        )
        out.append(f"| {mark} | **{_escape(row.prompt_id)}**<br>"
                   f"{_escape(row.prompt)} | {cells} |")

    changed = comparison.changed
    if changed:
        out += ["", "## What moved", ""]
        for row in changed:
            out += [f"### {row.prompt_id}", "", f"> {_escape(row.prompt)}", ""]
            for column, response in zip(comparison.columns, row.responses):
                out += [f"**{column.heading}**", "",
                        "```text", (response if response is not None
                                    else "(this run has no result for it)"), "```", ""]

    out += ["", "---", "",
            "_Generated by understudy. `~` means the wording changed but the "
            "answer did not; `!` means it moved._"]
    return "\n".join(out) + "\n"


def render_html(comparison: Comparison) -> str:
    rows = []
    for row in _ordered(comparison):
        mark, title = MARKS[row.verdict]
        cells = "".join(
            f'<td>{"<em>no run</em>" if r is None else _e(r) or "<em>nothing</em>"}</td>'
            for r in row.responses
        )
        rows.append(
            f'<tr class="{row.verdict}">'
            f'<td class="mark" title="{_e(title)}">{_e(mark)}</td>'
            f'<td><b>{_e(row.prompt_id)}</b><div class="lede">{_e(row.prompt)}</div></td>'
            f"{cells}</tr>"
        )

    heads = "".join(f"<th>{_e(c.heading)}<div class='lede'>{_e(c.label)}</div></th>"
                    for c in comparison.columns)
    warning = ""
    if comparison.mixed_flows:
        warning = (f'<p class="note">These runs are of different flows '
                   f'({_e(", ".join(comparison.flows))}). Rows are matched on '
                   f'prompt id, which may not mean what you want.</p>')

    return (
        '<!doctype html>\n<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>Comparison</title><style>{STYLE}{EXTRA}</style>"
        f"<script>{THEME_SCRIPT}</script></head><body><main>"
        f"<h1>Comparison</h1>{warning}"
        f'<p class="meta"><b>{_e(comparison.headline())}</b></p>'
        f'<div class="wrap"><table><thead><tr><th></th><th>prompt</th>{heads}'
        f"</tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
        "<footer>Generated by understudy. <code>~</code> means the wording "
        "changed but the answer did not; <code>!</code> means it moved."
        "</footer></main></body></html>\n"
    )


EXTRA = """
td.mark { width:22px; text-align:center; font-weight:700; }
tr.changed td.mark { color:var(--bad); }
tr.failed  td.mark { color:var(--bad); }
tr.missing td.mark { color:var(--warn); }
tr.reworded td.mark { color:var(--dim); }
tr.changed { background:rgba(224,92,92,.07); }
tr.failed  { background:rgba(224,92,92,.12); }
tbody td { vertical-align:top; }
tbody td div.lede { margin:2px 0 0; font-size:12px; }
"""


def _ordered(comparison: Comparison) -> list[Row]:
    """Changed first. Burying the two rows that moved among ninety that did
    not is how a comparison stops being read."""
    rank = {"changed": 0, "failed": 1, "missing": 2, "reworded": 3, "same": 4}
    return sorted(comparison.rows, key=lambda r: rank[r.verdict])


def _escape(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def write_comparison(comparison: Comparison, out: Path | str) -> list[Path]:
    out = Path(out)
    if out.suffix:
        stem, directory = out.stem, out.parent
    else:
        stem, directory = "comparison", out
    directory.mkdir(parents=True, exist_ok=True)

    markdown = directory / f"{stem}.md"
    page = directory / f"{stem}.html"
    markdown.write_text(render_markdown(comparison), encoding="utf-8")
    page.write_text(render_html(comparison), encoding="utf-8")
    return [markdown, page]
