"""The comparison, written out.

Markdown for a repository, HTML for the app and for printing. Same content:
one row per prompt, one column per run, labelled with what was under test.

Changed rows come first and are marked. A comparison that buries the two rows
that moved among ninety that did not is a comparison nobody reads twice.
"""

from __future__ import annotations

import html
import json
import os
from pathlib import Path

from understudy.compare import Comparison, Row
from understudy.transcript_html import STYLE, THEME_SCRIPT, _e

MARKS = {
    "same": ("", "unchanged"),
    "reworded": ("~", "same answer, worded differently"),
    "changed": ("!", "the answer moved"),
    "missing": ("?", "not present in every run"),
    "failed": ("x", "a run failed on this prompt"),
}


def render_markdown(comparison: Comparison) -> str:
    out = ["# Comparison", ""]
    if comparison.mixed_flows:
        out += [f"> **These runs are of different flows** "
                f"({', '.join(comparison.flows)}). The rows below are matched "
                f"on prompt id, which may not mean what you want.", ""]

    out += ["| run | under test | when |", "|---|---|---|"]
    for column in comparison.columns:
        out.append(f"| `{column.label}` | {column.subject.summary() or '—'} "
                   f"| {column.timestamp or '—'} |")

    out += ["", f"**{comparison.headline()}**", ""]

    heads = " | ".join(_escape(c.heading) for c in comparison.columns)
    rules = "|".join(["---"] * (len(comparison.columns) + 2))
    out += [f"| | prompt | {heads} |", f"|{rules}|"]

    for row in _ordered(comparison):
        mark = MARKS[row.verdict][0]
        cells = " | ".join(
            "_(no run)_" if r is None else _escape(r) or "_(nothing)_"
            for r in row.responses
        )
        out.append(f"| {mark} | **{_escape(row.prompt_id)}**<br>"
                   f"{_escape(row.prompt)} | {cells} |")

    changed = comparison.changed
    if changed:
        out += ["", "## What moved", ""]
        for row in changed:
            out += [f"### {row.prompt_id}", "", f"> {_escape(row.prompt)}", ""]
            for column, response in zip(comparison.columns, row.responses):
                out += [f"**{column.heading}**", "",
                        "```text", (response if response is not None
                                    else "(this run has no result for it)"), "```", ""]

    out += ["", "---", "",
            "_Generated by understudy. `~` means the wording changed but the "
            "answer did not; `!` means it moved._"]
    return "\n".join(out) + "\n"


def _stepper_data(comparison: Comparison, out_dir: Path | None) -> dict:
    """Everything the stepper needs, with image paths rewritten to be relative
    to wherever the page is written."""
    prefixes = []
    for column in comparison.columns:
        if out_dir is None:
            prefixes.append("")
            continue
        try:
            prefixes.append(os.path.relpath(column.run_dir, out_dir).replace("\\", "/") + "/")
        except ValueError:
            # A different drive on Windows: an absolute path is all there is.
            prefixes.append(Path(column.run_dir).as_uri() + "/")

    prompts = {}
    for prompt_id, per_column in comparison.steps.items():
        numbers = sorted({v.number for column in per_column for v in column})
        prompts[prompt_id] = [
            {
                "number": number,
                "description": next(
                    (v.description for column in per_column
                     for v in column if v.number == number), ""),
                "runs": [
                    _step_payload(next((v for v in column if v.number == number), None),
                                  prefixes[index])
                    for index, column in enumerate(per_column)
                ],
            }
            for number in numbers
        ]
    return {
        "columns": [c.heading for c in comparison.columns],
        "prompts": prompts,
    }


def _step_payload(view, prefix: str) -> dict:
    if view is None:
        return {"missing": True}
    return {
        "missing": False,
        "status": view.status,
        "ms": view.duration_ms,
        "typed": view.typed,
        "response": view.response,
        "shot": (prefix + view.screenshot) if view.screenshot else "",
    }


STEPPER_SCRIPT = """
(() => {
  const data = window.__comparison;
  if (!data || !Object.keys(data.prompts).length) return;
  const pick = document.getElementById('stepPrompt');
  const slider = document.getElementById('stepSlider');
  const caption = document.getElementById('stepCaption');
  const panes = document.getElementById('stepPanes');
  const counter = document.getElementById('stepCounter');

  pick.innerHTML = Object.keys(data.prompts)
    .map((id) => `<option>${id}</option>`).join('');

  let steps = [], at = 0;

  function draw() {
    const step = steps[at];
    if (!step) return;
    counter.textContent = `step ${step.number} of ${steps.length}`;
    caption.textContent = step.description || '';
    slider.max = String(steps.length - 1);
    slider.value = String(at);
    panes.innerHTML = step.runs.map((run, index) => {
      if (run.missing) {
        return `<figure><div class="absent">this run has no step ${step.number}</div>
          <figcaption>${data.columns[index]}</figcaption></figure>`;
      }
      const extra = [run.typed ? `typed: ${run.typed}` : '',
                     run.response ? `read: ${run.response}` : '',
                     run.status !== 'ok' ? run.status : ''].filter(Boolean).join(' · ');
      const shot = run.shot
        ? `<img src="${run.shot}" alt="step ${step.number}" loading="lazy">`
        : `<div class="absent">no screenshot at this step</div>`;
      return `<figure>${shot}<figcaption><b>${data.columns[index]}</b>
        <div class="lede">${run.ms} ms${extra ? ' · ' + extra : ''}</div>
        </figcaption></figure>`;
    }).join('');
  }

  function load() {
    steps = data.prompts[pick.value] || [];
    at = 0;
    draw();
  }
  function move(by) {
    at = Math.max(0, Math.min(steps.length - 1, at + by));
    draw();
  }

  pick.onchange = load;
  slider.oninput = () => { at = Number(slider.value); draw(); };
  document.getElementById('stepPrev').onclick = () => move(-1);
  document.getElementById('stepNext').onclick = () => move(1);
  // Arrow keys, because that is what anybody stepping through anything tries
  // first. Ignored while a control has focus so the select still works.
  addEventListener('keydown', (event) => {
    if (['INPUT', 'SELECT', 'TEXTAREA'].includes(document.activeElement.tagName)) return;
    if (event.key === 'ArrowLeft') { move(-1); event.preventDefault(); }
    if (event.key === 'ArrowRight') { move(1); event.preventDefault(); }
  });
  load();
})();
"""


def _stepper_markup(comparison: Comparison) -> str:
    if not comparison.steps:
        return ""
    return (
        '<h2 class="stepper">Step through</h2>'
        '<p class="lede">The same step of each run, side by side. The divergence '
        'worth finding is often visual and several steps before the answer — a '
        'dialog that opened somewhere else, a field that did not clear. Arrow '
        'keys work.</p>'
        '<div class="row step-controls">'
        '<select id="stepPrompt"></select>'
        '<button id="stepPrev" type="button">‹ Back</button>'
        '<button id="stepNext" type="button">Next ›</button>'
        '<span id="stepCounter" class="lede"></span>'
        '<input id="stepSlider" type="range" min="0" value="0">'
        "</div>"
        '<p id="stepCaption" class="step-caption"></p>'
        '<div id="stepPanes" class="step-panes"></div>'
    )


def render_html(comparison: Comparison, out_dir: Path | None = None) -> str:
    rows = []
    for row in _ordered(comparison):
        mark, title = MARKS[row.verdict]
        cells = "".join(
            f'<td>{"<em>no run</em>" if r is None else _e(r) or "<em>nothing</em>"}</td>'
            for r in row.responses
        )
        rows.append(
            f'<tr class="{row.verdict}">'
            f'<td class="mark" title="{_e(title)}">{_e(mark)}</td>'
            f'<td><b>{_e(row.prompt_id)}</b><div class="lede">{_e(row.prompt)}</div></td>'
            f"{cells}</tr>"
        )

    heads = "".join(f"<th>{_e(c.heading)}<div class='lede'>{_e(c.label)}</div></th>"
                    for c in comparison.columns)
    warning = ""
    if comparison.mixed_flows:
        warning = (f'<p class="note">These runs are of different flows '
                   f'({_e(", ".join(comparison.flows))}). Rows are matched on '
                   f'prompt id, which may not mean what you want.</p>')

    return (
        '<!doctype html>\n<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>Comparison</title><style>{STYLE}{EXTRA}</style>"
        f"<script>{THEME_SCRIPT}</script></head><body><main>"
        f"<h1>Comparison</h1>{warning}"
        f'<p class="meta"><b>{_e(comparison.headline())}</b></p>'
        f'<div class="wrap"><table><thead><tr><th></th><th>prompt</th>{heads}'
        f"</tr></thead><tbody>{''.join(rows)}</tbody></table></div>"
        f"{_stepper_markup(comparison)}"
        "<footer>Generated by understudy. <code>~</code> means the wording "
        "changed but the answer did not; <code>!</code> means it moved."
        "</footer></main>"
        f"<script>window.__comparison = "
        f"{json.dumps(_stepper_data(comparison, out_dir))};</script>"
        f"<script>{STEPPER_SCRIPT}</script>"
        "</body></html>\n"
    )


EXTRA = """
td.mark { width:22px; text-align:center; font-weight:700; }
tr.changed td.mark { color:var(--bad); }
tr.failed  td.mark { color:var(--bad); }
tr.missing td.mark { color:var(--warn); }
tr.reworded td.mark { color:var(--dim); }
tr.changed { background:rgba(224,92,92,.07); }
tr.failed  { background:rgba(224,92,92,.12); }
tbody td { vertical-align:top; }
tbody td div.lede { margin:2px 0 0; font-size:12px; }

h2.stepper { break-before:auto; }
.step-controls { display:flex; align-items:center; gap:10px; flex-wrap:wrap;
                 margin:10px 0; }
.step-controls select, .step-controls button {
  background:var(--panel); color:var(--fg); border:1px solid var(--line);
  border-radius:5px; padding:5px 12px; font:inherit; cursor:pointer; }
.step-controls input[type=range] { flex:1; min-width:160px; accent-color:var(--accent); }
.step-caption { font-weight:600; margin:2px 0 10px; }
.step-panes { display:grid; grid-template-columns:repeat(auto-fit, minmax(280px, 1fr));
              gap:14px; align-items:start; }
.step-panes figure { margin:0; }
.step-panes img { width:100%; border:1px solid var(--line); border-radius:6px;
                  display:block; }
.step-panes .absent { border:1px dashed var(--line); border-radius:6px;
                      padding:34px 12px; text-align:center; color:var(--dim);
                      font-size:12px; }
@media print { .step-controls { display:none; } }
"""


def _ordered(comparison: Comparison) -> list[Row]:
    """Changed first. Burying the two rows that moved among ninety that did
    not is how a comparison stops being read."""
    rank = {"changed": 0, "failed": 1, "missing": 2, "reworded": 3, "same": 4}
    return sorted(comparison.rows, key=lambda r: rank[r.verdict])


def _escape(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def write_comparison(comparison: Comparison, out: Path | str) -> list[Path]:
    out = Path(out)
    if out.suffix:
        stem, directory = out.stem, out.parent
    else:
        stem, directory = "comparison", out
    directory.mkdir(parents=True, exist_ok=True)

    markdown = directory / f"{stem}.md"
    page = directory / f"{stem}.html"
    markdown.write_text(render_markdown(comparison), encoding="utf-8")
    page.write_text(render_html(comparison, out_dir=directory), encoding="utf-8")
    return [markdown, page]
