#!/usr/bin/env python3
"""Look inside an embedded panel over CDP, and come out with a flow's targets.

The probe answers "can this be driven, and how". This answers the next
question: what is actually in there. Attach to a debugging endpoint an
application has left open -- a WebView2 or CEF panel inside CATIA or
3DEXPERIENCE -- walk every page and frame, and report the elements a flow
would name: where a prompt is typed, what submits it, and where the answer
appears.

    python inspect_cdp.py
    python inspect_cdp.py --cdp http://127.0.0.1:9222 --shots

It only reads and screenshots. It types nothing and clicks nothing.

Three things make this harder than listing inputs on a page:

  * The panel is usually not the top-level page. An embedded assistant is
    routinely an iframe inside an about:blank host, so a tool that looks only
    at document-level pages reports nothing and concludes there is nothing
    there.
  * Answers stream in. The element that will hold the response is often empty
    when you look, so it cannot be found by its text; it is found by being an
    aria-live region or a log role, which is what a chat UI marks it with.
  * A selector that works today should still work next release. So candidates
    are ranked by how stable the attribute is -- a test id outlives a class
    name, and a class name generated by a bundler outlives nothing.

Needs playwright (`pip install playwright`) but no browser download: it
attaches to a browser that is already running.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any

DEFAULT_CDP = "http://127.0.0.1:9222"

#: Attribute preference, most durable first. A data-testid is put there for
#: automation and survives a redesign; a class name from a CSS-in-JS bundler
#: changes when anything near it changes.
STABLE_ATTRIBUTES = ("data-testid", "data-test-id", "data-test", "data-cy",
                     "id", "name", "aria-label", "placeholder", "role")

# What a flow needs to name, and how to recognise each.
ENTRY = ("input:not([type=hidden]):not([type=checkbox]):not([type=radio]), "
         "textarea, [contenteditable=''], [contenteditable='true'], "
         "[role='textbox'], [role='combobox']")
SUBMIT = "button, [role='button'], input[type=submit]"
OUTPUT = ("[aria-live], [role='log'], [role='status'], [role='article'], "
          "[data-testid*='response'], [data-testid*='message'], "
          "[class*='response'], [class*='message'], [class*='answer']")

COLLECT = r"""
(selectors) => {
  const described = (el) => {
    const rect = el.getBoundingClientRect();
    const attrs = {};
    for (const attribute of el.attributes || []) {
      attrs[attribute.name] = String(attribute.value).slice(0, 120);
    }
    return {
      tag: el.tagName.toLowerCase(),
      attributes: attrs,
      text: (el.innerText || el.value || "").trim().slice(0, 120),
      box: {x: Math.round(rect.x), y: Math.round(rect.y),
            width: Math.round(rect.width), height: Math.round(rect.height)},
      visible: rect.width > 0 && rect.height > 0 &&
               getComputedStyle(el).visibility !== "hidden",
    };
  };
  const out = {};
  for (const [role, selector] of Object.entries(selectors)) {
    let found = [];
    try {
      found = Array.from(document.querySelectorAll(selector));
    } catch (error) {
      out[role] = [{error: String(error)}];
      continue;
    }
    out[role] = found.map(described).filter((e) => e.visible).slice(0, 40);
  }
  out.title = document.title;
  out.url = location.href;
  return out;
}
"""


def targets(cdp_url: str) -> list[dict[str, Any]]:
    """Every target the endpoint knows about, whatever its type.

    Not only pages: an embedded panel commonly shows up as an iframe or a
    webview target, and filtering to type == "page" is how you conclude a
    live panel is not there.
    """
    with urllib.request.urlopen(f"{cdp_url}/json/list", timeout=5) as response:
        listed = json.loads(response.read())
    return [t for t in listed if isinstance(t, dict)]


def selector_for(element: dict[str, Any]) -> str:
    """The most durable selector that identifies this element."""
    attributes = element.get("attributes") or {}
    for name in STABLE_ATTRIBUTES:
        value = attributes.get(name)
        if not value:
            continue
        if name == "id":
            return f"#{value}"
        if name == "role":
            # A role alone is rarely unique; qualified by the tag it often is.
            return f"{element['tag']}[role='{value}']"
        return f"[{name}='{value}']"
    classes = (attributes.get("class") or "").split()
    if classes:
        return f"{element['tag']}.{classes[0]}"
    return element["tag"]


def describe(element: dict[str, Any]) -> str:
    box = element.get("box") or {}
    text = element.get("text") or ""
    shown = f"  {text!r}" if text else ""
    return (f"{selector_for(element):<44} {element['tag']:<8} "
            f"{box.get('width', 0)}x{box.get('height', 0)}{shown}")


def inspect(cdp_url: str, out_dir: Path, shots: bool) -> dict[str, Any]:
    from playwright.sync_api import sync_playwright

    report: dict[str, Any] = {"cdp_url": cdp_url, "frames": []}
    with sync_playwright() as pw:
        browser = pw.chromium.connect_over_cdp(cdp_url)
        pages = [page for context in browser.contexts for page in context.pages]
        print(f"attached: {len(browser.contexts)} context(s), {len(pages)} page(s)")

        for index, page in enumerate(pages):
            try:
                page.wait_for_load_state("domcontentloaded", timeout=5000)
            except Exception:
                pass
            print(f"\npage {index}: {page.url}")
            if shots:
                try:
                    page.screenshot(path=str(out_dir / f"page-{index}.png"))
                except Exception as exc:
                    print(f"  (no screenshot: {str(exc)[:80]})")

            for frame in page.frames:
                try:
                    found = frame.evaluate(
                        COLLECT, {"entry": ENTRY, "submit": SUBMIT, "output": OUTPUT}
                    )
                except Exception as exc:
                    print(f"  frame {frame.url[:70]}: unreadable -- {str(exc)[:80]}")
                    continue

                counts = {role: len(found.get(role) or []) for role in
                          ("entry", "submit", "output")}
                if not any(counts.values()):
                    continue

                where = "  main frame" if frame is page.main_frame else "  iframe"
                print(f"{where}  {found['url'][:90]}")
                if found.get("title"):
                    print(f"    title: {found['title']!r}")
                for role, label in (("entry", "type into"),
                                    ("submit", "click to send"),
                                    ("output", "read from")):
                    elements = found.get(role) or []
                    if not elements:
                        continue
                    print(f"    {label}:")
                    for element in elements[:12]:
                        if "error" in element:
                            print(f"      ({element['error'][:80]})")
                            continue
                        print(f"      {describe(element)}")

                report["frames"].append({
                    "page": index, "page_url": page.url, "frame_url": found["url"],
                    "title": found.get("title", ""),
                    "is_main_frame": frame is page.main_frame,
                    **{role: found.get(role) or [] for role in
                       ("entry", "submit", "output")},
                })
        browser.close()
    return report


def suggest(report: dict[str, Any]) -> list[str]:
    """A flow's targets block, filled in with the best guesses.

    A guess: which of six buttons sends and which clears is not something to
    read off the DOM. It is a starting point to correct, which is faster than
    a starting point to write.
    """
    frame = next((f for f in report["frames"] if f.get("entry")), None)
    if not frame:
        return ["Nothing that takes typing was found. If LEO's panel was not open",
                "when this ran, open it and run again -- an unopened panel has no",
                "DOM to inspect."]

    lines = ["targets:"]
    lines += ["  prompt_box:", "    intent: the box the question is typed into",
              "    web:", f"      - css: \"{selector_for(frame['entry'][0])}\""]
    if frame.get("submit"):
        lines += ["  send:", "    intent: submits the question", "    web:",
                  f"      - css: \"{selector_for(frame['submit'][0])}\""]
    if frame.get("output"):
        lines += ["  answer:", "    intent: where the reply appears", "    web:",
                  f"      - css: \"{selector_for(frame['output'][0])}\""]
    if not frame["is_main_frame"]:
        lines += ["", f"# The panel is an iframe: {frame['frame_url'][:90]}",
                  "# Targets resolve inside it, not the host page."]
    return lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cdp", default=DEFAULT_CDP)
    parser.add_argument("--shots", action="store_true",
                        help="screenshot each page, to read the DOM against pixels")
    parser.add_argument("--out", default=None)
    args = parser.parse_args(argv)

    stamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    out_dir = Path(args.out or f"cdp-{stamp}")
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        listed = targets(args.cdp)
    except Exception as exc:
        print(f"no endpoint at {args.cdp}: {exc}", file=sys.stderr)
        return 1

    print(f"{len(listed)} target(s) at {args.cdp}:")
    for target in listed:
        print(f"  {target.get('type', '?'):<10} {str(target.get('title', ''))[:40]!r:<44}"
              f" {str(target.get('url', ''))[:80]}")
    (out_dir / "targets.json").write_text(json.dumps(listed, indent=2), encoding="utf-8")

    try:
        report = inspect(args.cdp, out_dir, args.shots)
    except ImportError:
        print("\nplaywright is not installed, so only the target list above was\n"
              "read. pip install playwright -- no browser download is needed,\n"
              "it attaches to the one already running.", file=sys.stderr)
        return 1

    (out_dir / "elements.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print("\n" + "\n".join(suggest(report)))
    print(f"\nwritten to {out_dir}/ -- send elements.json back")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
