#!/usr/bin/env python3
"""Look inside an embedded panel over CDP, and come out with a flow's targets.

The probe answers "can this be driven, and how". This answers the next
question: what is actually in there. Attach to a debugging endpoint an
application has left open -- a WebView2 or CEF panel inside CATIA or
3DEXPERIENCE -- walk every page and frame, and report the elements a flow
would name: where a prompt is typed, what submits it, and where the answer
appears.

    python inspect_cdp.py
    python inspect_cdp.py --cdp http://127.0.0.1:9222 --shots

It only reads and screenshots. It types nothing and clicks nothing.

Three things make this harder than listing inputs on a page:

  * The panel is usually not the top-level page. An embedded assistant is
    routinely an iframe inside an about:blank host, so a tool that looks only
    at document-level pages reports nothing and concludes there is nothing
    there.
  * Answers stream in. The element that will hold the response is often empty
    when you look, so it cannot be found by its text; it is found by being an
    aria-live region or a log role, which is what a chat UI marks it with.
  * A selector that works today should still work next release. So candidates
    are ranked by how stable the attribute is -- a test id outlives a class
    name, and a class name generated by a bundler outlives nothing.

Needs playwright (`pip install playwright`) but no browser download: it
attaches to a browser that is already running.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any

DEFAULT_CDP = "http://127.0.0.1:9222"

#: Attribute preference, most durable first. A data-testid is put there for
#: automation and survives a redesign; a class name from a CSS-in-JS bundler
#: changes when anything near it changes.
STABLE_ATTRIBUTES = ("data-testid", "data-test-id", "data-test", "data-cy",
                     "id", "name", "aria-label", "placeholder", "role")

# What a flow needs to name, and how to recognise each.
ENTRY = ("input:not([type=hidden]):not([type=checkbox]):not([type=radio]), "
         "textarea, [contenteditable=''], [contenteditable='true'], "
         "[role='textbox'], [role='combobox']")
SUBMIT = "button, [role='button'], input[type=submit]"
OUTPUT = ("[aria-live], [role='log'], [role='status'], [role='article'], "
          "[data-testid*='response'], [data-testid*='message'], "
          "[class*='response'], [class*='message'], [class*='answer']")

COLLECT = r"""
(selectors) => {
  // Every element, crossing open shadow boundaries. document.querySelectorAll
  // stops at the first shadow root, so against a panel built from custom
  // elements -- which is how a component framework builds one -- it reports a
  // page full of content as empty.
  const everything = [];
  const walk = (root, depth) => {
    if (depth > 30) return;
    let found;
    try { found = root.querySelectorAll("*"); } catch (error) { return; }
    for (const element of found) {
      everything.push(element);
      if (element.shadowRoot) walk(element.shadowRoot, depth + 1);
    }
  };
  walk(document, 0);

  const described = (el) => {
    const rect = el.getBoundingClientRect();
    const attrs = {};
    for (const attribute of el.attributes || []) {
      attrs[attribute.name] = String(attribute.value).slice(0, 120);
    }
    return {
      tag: el.tagName.toLowerCase(),
      attributes: attrs,
      text: (el.innerText || el.value || "").trim().slice(0, 120),
      box: {x: Math.round(rect.x), y: Math.round(rect.y),
            width: Math.round(rect.width), height: Math.round(rect.height)},
      shadowed: el.getRootNode() !== document,
      visible: rect.width > 0 && rect.height > 0 &&
               getComputedStyle(el).visibility !== "hidden",
    };
  };

  const out = {};
  for (const [role, selector] of Object.entries(selectors)) {
    out[role] = everything
      .filter((el) => { try { return el.matches(selector); } catch (e) { return false; } })
      .map(described)
      .filter((e) => e.visible)
      .slice(0, 40);
  }
  out.title = document.title;
  out.url = location.href;
  // What is actually in here, so "nothing matched" and "nothing here" can be
  // told apart without guessing.
  out.stats = {
    elements: everything.length,
    shadow_roots: everything.filter((el) => el.shadowRoot).length,
    text_length: (document.body && document.body.innerText || "").length,
    custom_elements: [...new Set(everything
      .filter((el) => el.tagName.includes("-"))
      .map((el) => el.tagName.toLowerCase()))].slice(0, 20),
  };
  return out;
}
"""


def endpoints(ports: list[int] | None = None) -> list[str]:
    """Every debugging endpoint on this machine, not just the well-known one.

    A host that creates several WebView2 environments and is told to use one
    port gives it to whichever starts first; the rest get none. Launched with
    --remote-debugging-port=0 they each take a free port instead, and then
    there is no port to guess -- so ask the machine what is listening and try
    all of it.
    """
    import probe_native

    owners = probe_native.listening_ports()
    candidates = sorted(set(ports if ports is not None
                            else list(owners) + probe_native.DEFAULT_PORTS))
    found = probe_native.probe_cdp(candidates, owners=owners,
                                   names=probe_native.process_names(), timeout=0.5)
    return [endpoint["cdp_url"] for endpoint in found]


def targets(cdp_url: str) -> list[dict[str, Any]]:
    """Every target the endpoint knows about, whatever its type.

    Not only pages: an embedded panel commonly shows up as an iframe or a
    webview target, and filtering to type == "page" is how you conclude a
    live panel is not there.
    """
    with urllib.request.urlopen(f"{cdp_url}/json/list", timeout=5) as response:
        listed = json.loads(response.read())
    return [t for t in listed if isinstance(t, dict)]


def selector_for(element: dict[str, Any]) -> str:
    """The most durable selector that identifies this element."""
    attributes = element.get("attributes") or {}
    for name in STABLE_ATTRIBUTES:
        value = attributes.get(name)
        if not value:
            continue
        if name == "id":
            return f"#{value}"
        if name == "role":
            # A role alone is rarely unique; qualified by the tag it often is.
            return f"{element['tag']}[role='{value}']"
        return f"[{name}='{value}']"
    classes = (attributes.get("class") or "").split()
    if classes:
        return f"{element['tag']}.{classes[0]}"
    return element["tag"]


def describe(element: dict[str, Any]) -> str:
    box = element.get("box") or {}
    text = element.get("text") or ""
    shown = f"  {text!r}" if text else ""
    return (f"{selector_for(element):<44} {element['tag']:<8} "
            f"{box.get('width', 0)}x{box.get('height', 0)}{shown}")


def inspect(cdp_url: str, out_dir: Path, shots: bool) -> dict[str, Any]:
    from playwright.sync_api import sync_playwright

    report: dict[str, Any] = {"cdp_url": cdp_url, "frames": []}
    with sync_playwright() as pw:
        browser = pw.chromium.connect_over_cdp(cdp_url)
        pages = [page for context in browser.contexts for page in context.pages]
        print(f"attached: {len(browser.contexts)} context(s), {len(pages)} page(s)")

        for index, page in enumerate(pages):
            try:
                page.wait_for_load_state("domcontentloaded", timeout=5000)
            except Exception:
                pass
            print(f"\npage {index}: {page.url}  ({len(page.frames)} frame(s))")
            if shots:
                try:
                    page.screenshot(path=str(out_dir / f"page-{index}.png"))
                except Exception as exc:
                    print(f"  (no screenshot: {str(exc)[:80]})")

            for frame in page.frames:
                try:
                    found = frame.evaluate(
                        COLLECT, {"entry": ENTRY, "submit": SUBMIT, "output": OUTPUT}
                    )
                except Exception as exc:
                    print(f"  frame {frame.url[:70]}: unreadable -- {str(exc)[:80]}")
                    continue

                counts = {role: len(found.get(role) or []) for role in
                          ("entry", "submit", "output")}
                stats = found.get("stats") or {}
                where = "  main frame" if frame is page.main_frame else "  iframe"
                summary = (f"{stats.get('elements', 0)} elements, "
                           f"{stats.get('shadow_roots', 0)} shadow roots, "
                           f"{stats.get('text_length', 0)} chars of text")
                if not any(counts.values()):
                    # Said out loud. "No frames at all" and "frames holding
                    # nothing I recognise" are completely different findings,
                    # and staying silent about the second makes them look the
                    # same to whoever is reading this on the workstation.
                    print(f"{where}  {found['url'][:90]}  -- {summary}, "
                          f"nothing matched")
                    if stats.get("custom_elements"):
                        print(f"      custom elements: "
                              f"{', '.join(stats['custom_elements'][:8])}")
                    report["frames"].append({
                        "page": index, "page_url": page.url,
                        "frame_url": found["url"], "title": found.get("title", ""),
                        "is_main_frame": frame is page.main_frame,
                        "stats": stats,
                        "entry": [], "submit": [], "output": [],
                        "empty": not stats.get("elements"),
                    })
                    continue

                print(f"{where}  {found['url'][:90]}  -- {summary}")
                if found.get("title"):
                    print(f"    title: {found['title']!r}")
                for role, label in (("entry", "type into"),
                                    ("submit", "click to send"),
                                    ("output", "read from")):
                    elements = found.get(role) or []
                    if not elements:
                        continue
                    print(f"    {label}:")
                    for element in elements[:12]:
                        if "error" in element:
                            print(f"      ({element['error'][:80]})")
                            continue
                        print(f"      {describe(element)}")

                report["frames"].append({
                    "page": index, "page_url": page.url, "frame_url": found["url"],
                    "title": found.get("title", ""),
                    "is_main_frame": frame is page.main_frame,
                    "stats": stats,
                    **{role: found.get(role) or [] for role in
                       ("entry", "submit", "output")},
                })
        browser.close()
    return report


def suggest(report: dict[str, Any]) -> list[str]:
    """A flow's targets block, filled in with the best guesses.

    A guess: which of six buttons sends and which clears is not something to
    read off the DOM. It is a starting point to correct, which is faster than
    a starting point to write.
    """
    frame = next((f for f in report["frames"] if f.get("entry")), None)
    if not frame:
        occupied = [f for f in report["frames"]
                    if (f.get("stats") or {}).get("elements")]
        if occupied:
            biggest = max(occupied,
                          key=lambda f: f["stats"].get("elements", 0))
            return [
                f"Content is here -- {biggest['stats']['elements']} elements in "
                f"the largest frame -- but nothing in it takes typing.",
                "So the panel is one of these and its controls are not shaped",
                "like anything looked for. Send elements.json and a screenshot;",
                "the custom element names in it are usually enough to name a",
                "target by hand.",
            ]
        return ["Every frame is genuinely empty, so this endpoint is not the",
                "panel. If several WebView2 hosts were told to share one",
                "debugging port, only the first got it. Relaunch with",
                "--remote-debugging-port=0 so each takes its own, then run",
                "inspect_cdp.py --all."]

    lines = ["targets:"]
    lines += ["  prompt_box:", "    intent: the box the question is typed into",
              "    web:", f"      - css: \"{selector_for(frame['entry'][0])}\""]
    if frame.get("submit"):
        lines += ["  send:", "    intent: submits the question", "    web:",
                  f"      - css: \"{selector_for(frame['submit'][0])}\""]
    if frame.get("output"):
        lines += ["  answer:", "    intent: where the reply appears", "    web:",
                  f"      - css: \"{selector_for(frame['output'][0])}\""]
    if not frame["is_main_frame"]:
        lines += ["", f"# The panel is an iframe: {frame['frame_url'][:90]}",
                  "# Targets resolve inside it, not the host page."]
    return lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cdp", default=DEFAULT_CDP)
    parser.add_argument("--all", action="store_true",
                        help="find every debugging endpoint on this machine and "
                             "inspect each, rather than only --cdp")
    parser.add_argument("--shots", action="store_true",
                        help="screenshot each page, to read the DOM against pixels")
    parser.add_argument("--out", default=None)
    args = parser.parse_args(argv)

    stamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    root = Path(args.out or f"cdp-{stamp}")
    root.mkdir(parents=True, exist_ok=True)

    if args.all:
        found = endpoints()
        if not found:
            print("no debugging endpoint anywhere on this machine.",
                  file=sys.stderr)
            return 1
        print(f"{len(found)} endpoint(s): {', '.join(found)}\n")
        failures = 0
        for endpoint in found:
            print("=" * 72)
            print(endpoint)
            print("=" * 72)
            failures += one(endpoint, root / endpoint.rsplit(":", 1)[-1], args.shots)
        return 1 if failures == len(found) else 0

    return one(args.cdp, root, args.shots)


def one(cdp_url: str, out_dir: Path, shots: bool) -> int:
    out_dir.mkdir(parents=True, exist_ok=True)
    try:
        listed = targets(cdp_url)
    except Exception as exc:
        print(f"no endpoint at {cdp_url}: {exc}", file=sys.stderr)
        return 1
    print(f"{len(listed)} target(s) at {cdp_url}:")
    for target in listed:
        print(f"  {target.get('type', '?'):<10} {str(target.get('title', ''))[:40]!r:<44}"
              f" {str(target.get('url', ''))[:80]}")
    (out_dir / "targets.json").write_text(json.dumps(listed, indent=2), encoding="utf-8")

    try:
        report = inspect(cdp_url, out_dir, shots)
    except ImportError:
        print("\nplaywright is not installed, so only the target list above was\n"
              "read. pip install playwright -- no browser download is needed,\n"
              "it attaches to the one already running.", file=sys.stderr)
        return 1

    (out_dir / "elements.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print("\n" + "\n".join(suggest(report)))
    print(f"\nwritten to {out_dir}/ -- send elements.json back")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
